site_name: SysteMatic Digital Commons

copyright: Copyright &copy; 2024 SysteMatic Project

nav:
  - Home: 'index.md'
  - About: 
    - 'about-systematic/index.md'
    - SysteMatic development phase: 'about-systematic/development-stage.md'
    - Navigating the Commons: 'about-systematic/commons-structure.md' 
  - Health Intelligence: 
    - 'health-intelligence/index.md'
    - Secondary care data - Glasgow: 'health-intelligence/glasgow.md'
    - Primary care data - Liverpool: 'health-intelligence/liverpool.md'
  - People Insights: 
    - 'people-insight/index.md'
    - Public involvement: 
      - PPIE blog: 'people-insight/public-involvement.md'
    - Patient involvement: 
      - MLTC activity books: 'people-insight/activity-book.md'
      - Arts-based workshops: 'people-insight/arts-based-workshops.md'
    - Person mapping: 
      - MLTC person maps: 'people-insight/person-maps.md'
      - Extremes and mainstreams: 'people-insight/extremes-mainstreams.md'
      - A set of systemic stories: 'people-insight/systemic-stories.md'
    - Journey mapping:
      - MLTC journey maps: 'people-insight/journey-maps.md'
    - Systems mapping: 
      - MLTC systems actor map: 'people-insight/actor-map.md'
    - Metaphors & images: 
      - Metaphors of MLTC lived experience: 'people-insight/metaphors.md'
  - Systems Science: 
    - 'systems-science/index.md'
    - 3 orders of MLTC systems science: 'systems-science/orders.md'
  - Transdisciplinary Synthesis & Strategy:
    - 'transdisciplinary-synthesis-strategy/index.md'
    - Problem definition: 'transdisciplinary-synthesis-strategy/problem-definition.md'
    - Problem prioritisation: 'transdisciplinary-synthesis-strategy/problem-prioritisation.md'
    - Sandpits: 
      - Liverpool MLTC system sandpit: 'transdisciplinary-synthesis-strategy/liverpool-sandpit.md'
    - MLTC learning system framework: 'transdisciplinary-synthesis-strategy/MLTC-learning-system-framework.md'
  - Publications: 'publications.md'
  - Glossary: 'glossary.md'
  
theme:
  name: material
  logo: 'assets/logo.png'
  palette:
    scheme: systematic
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - content.tabs.link
    - content.tabs
    - navigation.path
    - navigation.top
    
extra_css:
  - stylesheets/extra.css
  
markdown_extensions: 
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.blocks.caption
  - footnotes

plugins:
  - glightbox
  - search
  - tags:
      tags_file: tags.md
